# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: TimeWarpEnterprises

steps:
- task: DotNetCoreCLI@2
  displayName: Publish The Server project which will be deployed to azure
  inputs:
    command: run
    publishWebProjects: false
    projects: 'Source/TheFreezeTeamBlog/TheFreezeTeamBlog.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact to Output
  inputs:
    PathtoPublish: 'Source/TheFreezeTeamBlog/output'
    ArtifactName: Output
    publishLocation: Container
