trigger:
- master

stages:
  - stage: Build
    jobs:
    - job: Build

      pool:
        name: TimeWarpEnterprises

      steps:
      - task: DotNetCoreCLI@2
        displayName: Publish The Server project which will be deployed to azure
        inputs:
          command: run
          publishWebProjects: false
          projects: 'Source/TheFreezeTeamBlog/TheFreezeTeamBlog.csproj'

      - task: PublishBuildArtifacts@1
        displayName: Publish Artifact to Output
        inputs:
          PathtoPublish: 'Source/TheFreezeTeamBlog/output'
          ArtifactName: Output
          publishLocation: Container

  - stage: Production
    jobs:
      - deployment:
        pool: TimeWarpEnterprises
        environment: Production

        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Azure Web App Deploy: FreezeTeam'
                  inputs:
                    azureSubscription: 'TimeWarp Enterprises MSDN (00383693-c163-4094-aefb-f9b845833c21)'
                    appType: webApp
                    appName: FreezeTeam
