# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

queue:
  name: TimeWarpEnterprises

steps:
- script: wyam
  displayName: 'Run wyam to generate the output'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact to Output
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/output'
    ArtifactName: Output
    publishLocation: Container

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
