MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.3"
SiteTitle: The Freeze Team
Host: "thefreezeteam.com"
PostSources: posts/**
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
Layout: /_layout.cshtml
DateTimeInputCulture: en-US
CoverImageUrl: |
  =>
  {
    var image = Document.GetString(WebKeys.Image);
    if (image == null) return null;
    NormalizedPath x = new NormalizedPath(image);
    string result;
    if(x.IsRelative)
    {
      result = Context.GetLink(Document.Destination.ChangeFileName(image));
    } else
    {
      result = image;
    }
    return result;
  }
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
